import { Newspaper } from './types';

export const NEWSPAPERS: Newspaper[] = [
  // Italian Sources
  {
    id: 'televideo',
    name: 'Televideo RAI',
    description: "Italy's national broadcaster",
    url: 'https://www.servizitelevideo.rai.it/televideo/pub/solotesto.jsp',
    rssUrl: 'https://www.servizitelevideo.rai.it/televideo/pub/rss102.xml',
    fetchingMethod: 'rss',
    country: 'IT',
    flag: '🇮🇹',
  },
  {
    id: 'il-fatto',
    name: 'Il Fatto Quotidiano',
    description: 'Independent daily newspaper',
    url: 'https://www.ilfattoquotidiano.it/',
    rssUrl: 'https://www.ilfattoquotidiano.it/',
    fetchingMethod: 'scraping',
    selectors: ['h1', 'h2', 'h3', 'a.title'],
    country: 'IT',
    flag: '🇮🇹',
  },
  {
    id: 'repubblica',
    name: 'Repubblica',
    description: 'Major Italian newspaper',
    url: 'https://www.repubblica.it/',
    rssUrl: 'https://www.repubblica.it/',
    fetchingMethod: 'scraping',
    selectors: ['h1', 'h2', 'h3', 'article h2'],
    country: 'IT',
    flag: '🇮🇹',
  },
  {
    id: 'ansa',
    name: 'ANSA',
    description: 'Italian news agency',
    url: 'https://www.ansa.it/',
    rssUrl: 'https://www.ansa.it/',
    fetchingMethod: 'scraping',
    selectors: ['h1', 'h2', 'h3', '.title', 'article h3'],
    country: 'IT',
    flag: '🇮🇹',
  },
  {
    id: 'il-sole-24-ore',
    name: 'Il Sole 24 Ore',
    description: 'Financial and business news',
    url: 'https://www.ilsole24ore.com/',
    rssUrl: 'https://www.ilsole24ore.com/',
    fetchingMethod: 'scraping',
    selectors: ['h1', 'h2', 'h3', 'h4', 'a.title', 'div.title'],
    country: 'IT',
    flag: '🇮🇹',
  },
  {
    id: 'sky-tg24',
    name: 'SkyTg24',
    description: "Sky Italia's news channel",
    url: 'https://tg24.sky.it/',
    rssUrl: 'https://tg24.sky.it/',
    fetchingMethod: 'scraping',
    selectors: ['.c-card__title', '.c-hero__title', 'h2', 'h3', 'a.title'],
    country: 'IT',
    flag: '🇮🇹',
  },
  {
    id: 'internazionale',
    name: 'Internazionale',
    description: 'International magazine',
    url: 'https://www.internazionale.it/',
    rssUrl: 'https://www.internazionale.it/',
    fetchingMethod: 'scraping',
    selectors: ['h1', 'h2', 'h3', 'article h2', 'a.title'],
    country: 'IT',
    flag: '🇮🇹',
  },

  // German Sources
  {
    id: 'badische-zeitung',
    name: 'Badische Zeitung',
    description: 'Regional news from Baden',
    url: 'https://www.badische-zeitung.de/index.html',
    rssUrl: 'https://www.badische-zeitung.de/index.html',
    fetchingMethod: 'scraping',
    selectors: ['h1', 'h2', 'article h3', 'h3.headline'],
    country: 'DE',
    flag: '🇩🇪',
  },
  {
    id: 'dw',
    name: 'Deutsche Welle',
    description: "Germany's international broadcaster",
    url: 'https://www.dw.com/de/themen/s-9077',
    rssUrl: 'https://www.dw.com/de/themen/s-9077',
    fetchingMethod: 'scraping',
    selectors: ['h1', 'h2', 'h3', 'a h2', '.news h2'],
    country: 'DE',
    flag: '🇩🇪',
  },
  {
    id: 'tagesschau',
    name: 'Tagesschau',
    description: "ARD's news service",
    url: 'https://www.tagesschau.de/',
    rssUrl: 'https://www.tagesschau.de/',
    fetchingMethod: 'scraping',
    selectors: ['h1', 'h2', 'h3', '.teaser__headline', 'a h3'],
    country: 'DE',
    flag: '🇩🇪',
  },
  {
    id: 'sueddeutsche',
    name: 'Süddeutsche Zeitung',
    description: 'Leading German newspaper',
    url: 'https://www.sueddeutsche.de/',
    rssUrl: 'https://rss.sueddeutsche.de/rss/Topthemen',
    fetchingMethod: 'rss',
    country: 'DE',
    flag: '🇩🇪',
  },
  {
    id: 'faz',
    name: 'Frankfurter Allgemeine',
    description: 'Conservative German newspaper',
    url: 'https://www.faz.net/',
    rssUrl: 'https://www.faz.net/',
    fetchingMethod: 'scraping',
    selectors: ['h1', 'h2', 'h3', '.tsr-Base_HeadlineText', 'a.tsr-Base_HeadlineLink'],
    country: 'DE',
    flag: '🇩🇪',
  },
  {
    id: 'spiegel',
    name: 'Der Spiegel',
    description: 'German news magazine',
    url: 'https://www.spiegel.de/',
    rssUrl: 'https://www.spiegel.de/schlagzeilen/index.rss',
    fetchingMethod: 'rss',
    country: 'DE',
    flag: '🇩🇪',
  },

  // US Sources
  {
    id: 'reuters',
    name: 'Reuters',
    description: 'International news agency',
    url: 'https://www.reuters.com/',
    rssUrl: 'https://www.reuters.com/',
    fetchingMethod: 'scraping',
    selectors: ['h1', 'h2', 'h3', 'a[data-testid="Heading"]', 'span[data-testid="HeadingText"]'],
    country: 'US',
    flag: '🇺🇸',
  },
  {
    id: 'nytimes',
    name: 'New York Times',
    description: 'World section',
    url: 'https://www.nytimes.com/section/world',
    rssUrl: 'https://www.nytimes.com/section/world',
    fetchingMethod: 'scraping',
    selectors: ['h1', 'h2', 'h3', 'article h3', 'a h3'],
    country: 'US',
    flag: '🇺🇸',
  },
  {
    id: '68k-news-usa',
    name: '68k News USA',
    description: 'Technology focus',
    url: 'http://68k.news/index.php?section=nation&loc=US',
    rssUrl: 'http://68k.news/index.php?section=nation&loc=US',
    fetchingMethod: 'scraping',
    selectors: ['h1', 'h2', 'h3', 'a.title', 'td a'],
    country: 'US',
    flag: '🇺🇸',
  },
  {
    id: '68k-news-global',
    name: '68k News Global',
    description: 'International technology',
    url: 'http://68k.news/index.php?section=top&loc=US',
    rssUrl: 'http://68k.news/index.php?section=top&loc=US',
    fetchingMethod: 'scraping',
    selectors: ['h1', 'h2', 'h3', 'a.title', 'td a'],
    country: 'US',
    flag: '🇺🇸',
  },

  // European Sources
  {
    id: 'euronews',
    name: 'EuroNews',
    description: 'Pan-European news network',
    url: 'https://www.euronews.com/my-europe',
    rssUrl: 'https://www.euronews.com/my-europe',
    fetchingMethod: 'scraping',
    selectors: ['h1', 'h2', 'h3', '.m-object__title', 'a.m-object__title__link'],
    country: 'EU',
    flag: '🇪🇺',
  },

  // News Aggregators
  {
    id: 'agg-68k-it',
    name: '68k News Italy',
    description: 'Italian technology news',
    url: 'http://68k.news/index.php?section=nation&loc=IT',
    rssUrl: 'http://68k.news/index.php?section=nation&loc=IT',
    fetchingMethod: 'scraping',
    selectors: ['h1', 'h2', 'h3', 'a.title', 'td a'],
    country: 'AGG',
    flag: '🤖',
  },
  {
    id: 'agg-68k-de',
    name: '68k News Germany',
    description: 'German technology news',
    url: 'http://68k.news/index.php?section=nation&loc=DE',
    rssUrl: 'http://68k.news/index.php?section=nation&loc=DE',
    fetchingMethod: 'scraping',
    selectors: ['h1', 'h2', 'h3', 'a.title', 'td a'],
    country: 'AGG',
    flag: '🤖',
  },
  {
    id: 'agg-68k-us',
    name: '68k News USA',
    description: 'American technology news',
    url: 'http://68k.news/index.php?section=nation&loc=US',
    rssUrl: 'http://68k.news/index.php?section=nation&loc=US',
    fetchingMethod: 'scraping',
    selectors: ['h1', 'h2', 'h3', 'a.title', 'td a'],
    country: 'AGG',
    flag: '🤖',
  },

  // Music Sources
  {
    id: 'indie-for-bunnies',
    name: 'Indie For Bunnies',
    description: 'Independent music magazine',
    url: 'http://www.indieforbunnies.com/',
    rssUrl: 'http://www.indieforbunnies.com/',
    fetchingMethod: 'scraping',
    selectors: ['h2 a', 'h3 a', '.entry-title'],
    country: 'MUSIC',
    flag: '🎸',
  },
  {
    id: 'music-off',
    name: 'MusicOff',
    description: 'Musicians community',
    url: 'https://www.musicoff.com/',
    rssUrl: 'https://www.musicoff.com/feeds',
    fetchingMethod: 'rss',
    country: 'MUSIC',
    flag: '🎸',
  },
  {
    id: 'mtv-news',
    name: 'MTV News IT',
    description: 'Music and pop culture',
    url: 'http://news.mtv.it/',
    rssUrl: 'http://news.mtv.it/',
    fetchingMethod: 'scraping',
    selectors: ['h2', 'h3', 'a.title'],
    country: 'MUSIC',
    flag: '🎸',
  },
  {
    id: 'ondarock',
    name: 'OndaRock',
    description: 'Music reviews and rock culture',
    url: 'http://www.ondarock.it/',
    rssUrl: 'http://www.ondarock.it/',
    fetchingMethod: 'scraping',
    selectors: ['h2', 'h3', 'a'],
    country: 'MUSIC',
    flag: '🎸',
  },
  {
    id: 'rockit',
    name: 'Rockit',
    description: 'Italian independent music',
    url: 'https://www.rockit.it/',
    rssUrl: 'https://www.rockit.it/web/index.php',
    fetchingMethod: 'scraping',
    selectors: ['h2', 'h3', 'a.title'],
    country: 'MUSIC',
    flag: '🎸',
  },
  {
    id: 'rockol',
    name: 'Rockol',
    description: 'Music news and charts',
    url: 'https://www.rockol.it/',
    rssUrl: 'https://www.rockol.it/',
    fetchingMethod: 'scraping',
    selectors: ['h2', 'h3', 'a.title'],
    country: 'MUSIC',
    flag: '🎸',
  },
  {
    id: 'rolling-stone',
    name: 'Rolling Stone IT',
    description: 'Music and culture magazine',
    url: 'https://www.rollingstone.it/',
    rssUrl: 'https://www.rollingstone.it/',
    fetchingMethod: 'scraping',
    selectors: ['h2', 'h3', 'article h1'],
    country: 'MUSIC',
    flag: '🎸',
  },
  {
    id: 'soundsblog',
    name: 'Soundsblog',
    description: 'Music news and rumors',
    url: 'http://www.soundsblog.it/',
    rssUrl: 'http://www.soundsblog.it/',
    fetchingMethod: 'scraping',
    selectors: ['h2', 'h3', '.title'],
    country: 'MUSIC',
    flag: '🎸',
  },

  // Economy Sources
  {
    id: 'corriere-economia',
    name: 'Corriere Economia',
    description: 'Business and finance from Corriere',
    url: 'https://www.corriere.it/economia/',
    rssUrl: 'https://www.corriere.it/economia/',
    fetchingMethod: 'scraping',
    selectors: ['h2', 'h3', 'h4', 'a.title'],
    country: 'ECONOMY',
    flag: '📈',
  },
  {
    id: 'repubblica-economia',
    name: 'Repubblica Economia',
    description: 'Economy section of La Repubblica',
    url: 'http://www.repubblica.it/economia/',
    rssUrl: 'http://www.repubblica.it/economia/',
    fetchingMethod: 'scraping',
    selectors: ['h2', 'h3', 'article h2'],
    country: 'ECONOMY',
    flag: '📈',
  },
  {
    id: 'ansa-economia',
    name: 'ANSA Economia',
    description: 'Economic news from ANSA',
    url: 'http://www.ansa.it/sito/notizie/economia/economia.shtml',
    rssUrl: 'http://www.ansa.it/sito/notizie/economia/economia.shtml',
    fetchingMethod: 'scraping',
    selectors: ['h2', 'h3', '.title'],
    country: 'ECONOMY',
    flag: '📈',
  },
  {
    id: 'sole-finanza',
    name: 'Il Sole 24 Ore - Finanza',
    description: 'Finance news',
    url: 'https://www.ilsole24ore.com/',
    rssUrl: 'https://www.ilsole24ore.com/rss/finanza.xml',
    fetchingMethod: 'rss',
    country: 'ECONOMY',
    flag: '📈',
  },
  {
    id: 'sole-norme',
    name: 'Il Sole 24 Ore - Norme',
    description: 'Legal and tax news',
    url: 'https://www.ilsole24ore.com/',
    rssUrl: 'https://www.ilsole24ore.com/rss/norme-e-tributi.xml',
    fetchingMethod: 'rss',
    country: 'ECONOMY',
    flag: '📈',
  },
  {
    id: 'sole-risparmio',
    name: 'Il Sole 24 Ore - Risparmio',
    description: 'Personal finance news',
    url: 'https://www.ilsole24ore.com/',
    rssUrl: 'https://www.ilsole24ore.com/rss/risparmio.xml',
    fetchingMethod: 'rss',
    country: 'ECONOMY',
    flag: '📈',
  },
];
